### ISSUE TITLE
Gallant signals header guards conflicts on android NDK

### ISSUE THREAD

**Issue by scooterman** [pbhogan/Signals#2]
The file Signals.h defines it's header guard with:

```
 #ifndef _SIGNAL_H_
 #define _SIGNAL_H_
```

This name clashes on android NDK, making the header to not be included and thus making the lib unusable on it.

I could fix it myself and send a patch, if needed :)

Thanks,

**Comment by pbhogan** [comment]
Thanks. I've pushed up a fix.
