### ISSUE TITLE
License in Delegate.h looks wrong

### ISSUE THREAD

**Issue by starseeker** [pbhogan/Signals#6]
Your README and the article itself both specify the Delegate.h code as public domain, but the file itself claims it is under the Code Project Open License (CPOL) which is anything but public domain...

Would it be possible to update the license statement (if need be, clarifying with the authors that CPOL is not the licensing conditions for Delegate.h)?  If the CPOL is in the mix, code concerned about GPL compatibility is basically dead in the water as far as using Signals... :-(

**Comment by pbhogan** [comment]
Even though the site says the license is CPOL, in the [article](http://www.codeproject.com/Articles/7150/Member-Function-Pointers-and-the-Fastest-Possible) the author explicitly states under the heading "License,"

"The source code attached to this article is released into the public domain. You may use it for any purpose."

I've changed the license text in `Delegate.h` to clarify.
